# Site settings

remote_theme : bogoli/-folio

title: Marketing&IT Blog
email: stelch@naver.com
description: > # this means to ignore newlines until "baseurl:"
  마케팅 전공자의 데이터 분석 경험
baseurl:  # the subpath of your site, e.g. /blog/
url: https://stelch1234.github.io/ # the base hostname & protocol for your site
github_username:  stelch1234
google_analytics_id: UA-158965523-1    

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


